### ISSUE TITLE
Два бегунка спарва

### ISSUE THREAD

**Issue by kate-fsd** [Euyevnc/RangeSlider#10]
Когда оба бегунка справа, они не захватываются, пример:
Точка отсчёта : 0
Диапозон: 100
Шаг: 1

**Comment by Euyevnc** [comment]
Захватываться-то они захватываются, только крайний справа никуда сдвинуться не может, потому как "припёрт" первым, а первый еле выглядывает из-за второго, поэтому схватиться за него сложно, будешь цеплять второй. На гифке я добавил границы и теперь это хорошо видно. Мне тоже это не нравится, но решения хорошего не придумал, если ввести какое-то минимальное расстояние между ними, то будет нарушаться пропорция и некоторые значения будут визуально отображаться одинаково. Я думаю, что, опять же, в таких случаях, если имеют дело с большим рэньжом, просто выставляют шаги достаточно большие, чтобы такого не происходило. Для 100  шаг 5 уже помогает избежать таких проблем. Но если узнаю хорошее решение - исправлю. Пока просто не до чего не додумался особо(
![tum](https://user-images.githubusercontent.com/71395653/118387949-9a274780-b64b-11eb-9977-65d8da18192f.gif)

**Comment by kate-fsd** [comment]
Можно посчитать в какой момент левый бегунок заезжает под правый и ставить ему бОльший z index. Либо это можно сделать когда левый бегунок например в середине слайдера. Нужно потестировать
