### ISSUE TITLE
Баги и недочеты слайдера

### ISSUE THREAD

**Issue by mglknFSD** [Euyevnc/RangeSlider#30]
1 Тултипы (область над бегунком где отображается значение) то же должны быть интерактивными. Т е должна быть возможность перетащить бегунок за этот туттип.

**Comment by mglknFSD** [comment]
Что-то у меня не получается поменять шаг слайдера.

https://user-images.githubusercontent.com/75975369/133467560-c18c7cca-1731-4262-8200-870392afdf59.mp4

**Comment by Euyevnc** [comment]
Мы с прошлым ревьюером обсуждали работу с дробями. Решил, что лучше работать только с целыми числами. Ну, значения просто округляются при вычислении или задании значений. При работе с дробями просто встают вопросы с тем, какое число минимально возможным значением,  как выводить очень длинные дроби, которые постоянно вылезают, ну и красивого решения у этих задач нет, то есть я их не нашёл
Стоит добавить поддержку?

**Comment by mglknFSD** [comment]
> Мы с прошлым ревьюером обсуждали работу с дробями. Решил, что лучше работать только с целыми числами. Ну, значения просто округляются при вычислении или задании значений. При работе с дробями просто встают вопросы с тем, какое число минимально возможным значением, как выводить очень длинные дроби, которые постоянно вылезают, ну и красивого решения у этих задач нет, то есть я их не нашёл
> Стоит добавить поддержку?

По условию задания шаг может быть любым. И округлять ничего не надо, но значения должны вычисляться корректно. Это одно из особенностей этого задания.

**Comment by mglknFSD** [comment]
Еще небольшой баг.

https://user-images.githubusercontent.com/75975369/134766511-9a36e3ff-44db-4675-9680-1ccf9d42510d.mp4
