### ISSUE TITLE
Синхронизация

### ISSUE THREAD

**Issue by kate-fsd** [Euyevnc/RangeSlider#8]
Панель и слайдер должны быть синхронизированы. Если какие то данные не прошли валидацию, значение в панели должно измениться (например шаг 1000 если мин = 0, макс = 10). Также, после изменения шага бегунок должен оказаться на ближайшем допустимом, а не остаться там где стоял

**Comment by Euyevnc** [comment]
Ну, я думаю, что  с изменением шага бегунок не обязательно перемещать на допустимый, просто предусмотрено в слайдере, что значения можно задавать и вне разметки, это не будет ошибкой. Я просто не думаю, что это поведение всегда будет желательным. Да и шаг находится в конфиги, а значения старт - финиш хранятся и обрабатываются в Model,  о котором конфиг ничего не должен знать. Я думаю, лучше всего добавить публичный метод в Model, типа adaptValues, который будет приводить значения в соответствие с разметкой и вызывать её из панели при изменении шага

**Comment by Euyevnc** [comment]
Панель я со слайдером синхронизировал, для рэньжа, значений. Для шагов есть только нижнее ограничение, вполне можно поставить 100 при рэньже 10, только доступно тогда будет только максимальное и минимальное значение. Но только это всё происходит на уровне панели В конфиге валидация только во время создания объекта, не его изменений, думаешь стоит ввести, стоит это поменять? Просто я исхожу из того, что это всё-таки инструменты разработчика, который примерно понимает, что он делает. Если хочет установить рэньж в 0, то должен понимать, что ничего хорошего не произойдёт. Я стараюсь по-минимуму накладывать ограничения, только самые необходимые. Потому что тот кто пользуется плагином всегда может добавить их сторонним способом, но если какие-то из них не нужны, то вытащить их уже не получится

**Comment by kate-fsd** [comment]
"Для шагов есть только нижнее ограничение, вполне можно поставить 100 при рэньже 10" звучит не очень, лучше в таком случае уменьшить шаг и вывести сообщение предупреждение 

"во время создания объекта, не его изменений,"  во время изменения тоже должна быть валидация

"Просто я исхожу из того, что это всё-таки инструменты разработчика, который примерно понимает, что он делает."  не смотря на это все проверки на дурака должны быть

Сделай пожалуйста так, чтобы слайдер создавался и изменялся с любыми параметрами, если они не подходят - заменяй на те что в начальном конфиге. И лучше пользователю показывать сообщения, что именно он передал неправильно

**Comment by kate-fsd** [comment]
И все что написано в первом сообщении нужно выполнить)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/120940401-c9e6de00-c725-11eb-91e5-b082ab8a6089.png)

При таких параметрах бегунок должен ходить только по шагам 0, 9, 10

**Comment by kate-fsd** [comment]
Интервал не тот
![image](https://user-images.githubusercontent.com/66846004/120940885-3531af80-c728-11eb-9746-6f284efe8824.png)
